export const SET_SELECTED_PIECE = "SET_SELECTED_PIECE";

export const SET_DESTINATION_TILE = "SET_DESTINATION_TILE";

export const SET_PLAYER_PIECES = "SET_PLAYER_ONE_PIECES";

export const SET_OPPONENT_PIECES = "SET_PLAYER_TWO_PIECES";

export const SET_GAME_STATE = "SET_GAME_STATE";

export const SET_PLAYER_COLOR = "SET_PLAYER_COLOR";

export const SET_OPPONENT_COLOR = "SET_OPPONENT_COLOR"

export const SET_CLASH_ROLL = "SET_CLASH_ROLL";

export const SET_MOVE_STATUS = "SET_MOVE_STATUS";

export const SET_LOSER = "SET_LOSER";
